### ISSUE TITLE
Using Alpha in Loss function

### ISSUE THREAD

**Issue by chuong98** [Tangshitao/Semi-supervised-Adaptive-Distillation#1]
Hi, thanks for releasing the code.
In your paper, there is no mention about alpha parameter, but your code does.
Can you help to clarify the usage of alpha parameter?
For example, will you set alpha_t= alpha if positive anchor, and 1-alpha if negative anchor, just like the Focal loss.
Thanks.

**Comment by Tangshitao** [comment]
You can do this, but I just set alpha=0.5

**Comment by Tangshitao** [comment]
Yes, alpha is the same as focal loss
