### ISSUE TITLE
Curious about the improvement when training with enough data augmentation.

### ISSUE THREAD

**Issue by SpyderXu** [Tangshitao/Semi-supervised-Adaptive-Distillation#4]
Semi-supervised object detection is kind of data augmentation in a way, and detectron only provides simple flip and multi-scale training for data augmentation. So I am interested in the imporvement with the semi-supervised method when doing enough augmentations(multi-scale training or other).

**Comment by Tangshitao** [comment]
Not sure if it would work if strong augmentation is applied. Actually, I heard that some augmentation methods could improve 2-3 AP in retinanet, so it is very likely semi-supervised learning does not work in this setting.
