### ISSUE TITLE
How to run this codes?

### ISSUE THREAD

**Issue by UcanSee** [Tangshitao/Semi-supervised-Adaptive-Distillation#5]
Recently I read your paper 《Learning Efficient Detector with Semi-supervised Adaptive Distillation》，and I want to try this method. I have installed caffe2 by installing pytorch,  and I have installed Detectron and coco API. Then what I should do to run this codes? I found that I don't know how to use the two packages: caffe2 and detectron you commited. What should I do to reorganise the packages and run this codes successfully? Could you tell me the specific steps to run this code? Thank you very much!

**Comment by UcanSee** [comment]
There are some functions I have not found, like "register_teacher, register_student,register_cfg, restore_C" in train_net.py.  Where can I find it ?

**Comment by Tangshitao** [comment]
Hi, this is a very old version of caffe2 and detectron. You can compile them by the codes I provide or put the files I mentioned in the Readme to your version caffe2.
